# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "newsletters" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"version" BIGINT NOT NULL,"subject" VARCHAR(254) NOT NULL,"text" VARCHAR(254) NOT NULL,"status" INTEGER NOT NULL,"date_sent" TIMESTAMP,"date_created" TIMESTAMP NOT NULL,"date_updated" TIMESTAMP NOT NULL);
create table "reset_password_tokens" ("user_id" INTEGER NOT NULL PRIMARY KEY,"password_token" VARCHAR(254) NOT NULL);
create table "users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"version" BIGINT NOT NULL,"role" VARCHAR(254) NOT NULL,"email" VARCHAR(254) NOT NULL,"password" VARCHAR(254) NOT NULL,"date_created" TIMESTAMP NOT NULL,"date_updated" TIMESTAMP NOT NULL,"location" VARCHAR(254) NOT NULL,"latitude" DOUBLE PRECISION NOT NULL,"longitude" DOUBLE PRECISION NOT NULL);
create unique index "users_idx_a" on "users" ("email");
alter table "reset_password_tokens" add constraint "reset_password_tokens_user_fk" foreign key("user_id") references "users"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "reset_password_tokens" drop constraint "reset_password_tokens_user_fk";
drop table "users";
drop table "reset_password_tokens";
drop table "newsletters";

